### PR TITLE
RFC: Changes default fn_prefix in TrainEndCheckpoint to train_end_

### PR DESCRIPTION
**Pull request by thomasjpfan**
The default prefix for `TrainEndCheckpoint` is `final_`. This PR adjusts it to `train_end_` along with all the references to it.

### CODE REVIEW

**Comment by benjamin-work** [comment]
This change makes sense. In theory, it could break backwards compatibility for some users. I guess that's not too big of a concern since this code was introduced not too long ago. But if the next skorch release is far away, more people could be affected by then. Do we want to do anything about that?

**Comment by thomasjpfan** [comment]
The only good option I see is to leave the default as `final_` and issue a warning stating that the default will change in 0.5.0 or 0.6.0, depending when this PR gets released. I would hope a point release such as 0.4.1, so this default can change at 0.5.0.

**Comment by thomasjpfan** [comment]
This PR was updated to keep the default as `final_` but issue a `FutureWarning` stating the default will change in `0.5.0`.

**Comment by benjamin-work** [comment]
LGTM, @ottonemo what's your take?

**Comment by ottonemo** [comment]
LGTM, please document the change in the change log :)

**Pull request merged**
