### PR TITLE
[MRG] Update transform learning to use class in NeutralNet.__init__

### PR DESCRIPTION
**Pull request by thomasjpfan**
Updates tutorial to use a class in `NeutralNet.__init__`.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Could you quickly explain why you made that change?

**Comment by thomasjpfan** [comment]
Previously, the module was created first and passed to `NeuralNet`. This PR pushes the use of the stateless class to creating the `NeuralNet` object.

**Comment by BenjaminBossan** [comment]
Okay, so this is to encourage more "skorchy" usage. From my perspective, this is good to go, @ottonemo what do you think?

**Comment by ottonemo** [comment]
LGTM

**Pull request merged**
