### PR TITLE
ENH: Always adds batches to keys_ignored

### PR DESCRIPTION
**Pull request by thomasjpfan**
Fixes https://github.com/dnouri/skorch/issues/284.

### CODE REVIEW

**Comment by benjamin-work** [comment]
Thanks

**Comment by taketwo** [comment]
Perhaps this should have removed 'batches' from lines 13 and 124.

**Comment by benjamin-work** [comment]
@taketwo what do you mean?

**Comment by taketwo** [comment]
I meant these functions in `test_logging.py`:

```python
    def print_log_cls(self):
        from skorch.callbacks import PrintLog
        keys_ignored = ['batches', 'dur', 'text']
        return partial(PrintLog, sink=Mock(), keys_ignored=keys_ignored)
```

and

```python
    def test_with_additional_key(self, history, print_log_cls):
        keys_ignored = ['batches']  # 'dur' no longer ignored
```

No need to have `'batches'` in the ignored keys anymore.

**Pull request merged**
