### PR TITLE
DOC Adds FAQ entry on pytorch's Dataset

### PR DESCRIPTION
**Pull request by thomasjpfan**
Further addresses https://github.com/dnouri/skorch/issues/422 by adding a FAQ item and rewording the `Dataset` docs.

### CODE REVIEW

**Comment by taketwo** [comment]
I think the last paragraph in the new FAQ entry is not needed, predefined splits are already covered in a [separate entry](https://skorch.readthedocs.io/en/stable/user/FAQ.html#i-already-split-my-data-into-training-and-validation-sets-how-can-i-use-them).

**Comment by thomasjpfan** [comment]
The [separate entry](https://skorch.readthedocs.io/en/stable/user/FAQ.html#i-already-split-my-data-into-training-and-validation-sets-how-can-i-use-them) was targeted to using numpy arrays together with a skorch `Dataset` for a validation dataset. This PRs last paragraph is for using a PyTorch `Dataset`. I see users with a PyTorch's `Dataset` to already have defined a validation dataset, and the PR's last paragraph would help them use skorch.

**Comment by taketwo** [comment]
Mmm, but the entry I referred to literally says:

> If you have predefined training and validation datasets that are subclasses of PyTorch Dataset,

**Comment by thomasjpfan** [comment]
Ah I see. I am mistaken. This PR was updated to remove the last paragraph.

**Comment by BenjaminBossan** [comment]
LGTM

**Comment by BenjaminBossan** [comment]
Thank you.

**Pull request merged**
