### PR TITLE
DOC: Update to run in colab

### PR DESCRIPTION
**Pull request by thomasjpfan**
Addresses some of #316

You can see how this works here: https://colab.research.google.com/github/thomasjpfan/skorch/blob/transfer-learning-colab/notebooks/Transfer_Learning.ipynb

### CODE REVIEW

**Comment by benjamin-work** [comment]
As a colab newbie, do I have to do anything special before running the notebook? The imports fail for me because torch is not installed. The data download fails because there is

> No such file or directory: 'datasets/hymenoptera_data'

**Comment by thomasjpfan** [comment]
I forgot to add the download cell. I updated the notebook to install the dependencies and `wget` the data files.

**Comment by benjamin-work** [comment]
Now I could progress further but got this cuda error:

> RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74

Also could you make the download cell optional? Ideally, it should execute depending on the environment but I didn't see any env variable that signals that colab is used. Perhaps `DATALAB_ENV=GCE` can be used as a proxy?

**Comment by thomasjpfan** [comment]
I updated the PR by using `DATALAB_ENV` as a flag on the download cell.

I am unable to run into that error. Which cell do you run into the issue?

**Comment by thomasjpfan** [comment]
Checking the cuda version tensorflow is built on (in colab):

```bash
!cat /usr/local/lib/python3.6/dist-packages/tensorflow/include/external/local_config_cuda/cuda/cuda/cuda_config.h | grep TF_CUDA_VERSION
#define TF_CUDA_VERSION "8.0"
```

Does changing the `pip install...` line to the following fix your issue?

```
! [ "$DATALAB_ENV" = "GCE" ] && pip install http://download.pytorch.org/whl/cu80/torch-0.4.1-cp36-cp36m-linux_x86_64.whl torchvision skorch pillow==4.1.1
```

**Comment by benjamin-work** [comment]
I did not enable GPU, that may have caused the error.

Regarding the colab cell, could you add a comment to explain what this is and why it is needed?

**Comment by benjamin-work** [comment]
Thank you, nice addition.

**Pull request merged**
