### PR TITLE
Clean ups for release 0.3

### PR DESCRIPTION
**Pull request by benjamin-work**
* Remove deprecations related to use_cuda/device
* Add a missing space in error message.
* Improve docstring of to_tensor.
* Cosmetic: Add missing space after colon.

Addresses #250

### CODE REVIEW

**Comment by taketwo** [comment]
Does skorch have any deprecation policy? The `device` parameter was removed after 0.2 release, i.e. the deprecation warning was never a part of any release. Thus for those who stick with released versions you are effectively breaking interface without a warning.

**Comment by benjamin-work** [comment]
Technically, you are correct. The general changes (which were related to PyTorch 0.4) that resulted in the deprecation were in place in 0.2 but we forgot to adapt this part of the code (meaning it should have been in 0.2).

So we could extend the deprecation period. But perhaps this feature was used so little that we can get away with removing it nonetheless?

**Comment by taketwo** [comment]
This is a philosophical question; a clear deprecation policy would help to answer this.

Given that skorch is still in its 0.Xes... it's maybe kind of okay. Still, with 1.5K stars I suppose there are thousands of users, and there is a chance some of them still have this `device` around. IMHO it would be non-decent maintainership to break their code without warning and a grace period. Especially when it costs nothing to have this warning around.

**Comment by benjamin-work** [comment]
Our unofficial deprecation policy is to wait for 1 release, I believe at this stage moving fast is still okay.

I restored the warning in `Dataset` for the reasons you gave.

**Pull request merged**
