### PR TITLE
RFC: Splits callback tests into seperate files

### PR DESCRIPTION
**Pull request by thomasjpfan**
Refactors callback tests as suggested in #240.

### CODE REVIEW

**Comment by benjamin-work** [comment]
Thanks, I will look into this.

Just so that you know, I already started working on the other part (splitting net.py).

**Comment by benjamin-work** [comment]
We saw that you moved the tests for some classes to their own submodule (e.g. `test_print_log.py`). Could you instead mirror the module structure of `callbacks` for consistency?

At least for now, we want to keep the current structure. If in the future, we find that files become too crowded, we might change that, but for now, the existing structure looks good enough.

**Comment by thomasjpfan** [comment]
I updated this PR to mirror the `callbacks` structure.

**Comment by benjamin-work** [comment]
Looks good to me. Only the error is left to fix. I guess changing `from .conftest import` to `from ..conftest import` and puting an `__init__.py` into `skorch/tests/callbacks/` should do the job.

**Comment by thomasjpfan** [comment]
I refactored the two tests to use the pytest fixtures directly. This fixes the tests that was failing before.

**Comment by benjamin-work** [comment]
Yes, that's the better way.

Many thanks.

**Pull request merged**
