### PR TITLE
Attempt to merge setup dependencies

### PR DESCRIPTION
**Pull request by ottonemo**
WIP to merge the requirements.txt and requirements in setup.py.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
The only issue blocking this is how tabulate is not in conda. Moving scikit-learn and tqdm to `requirements-dev.txt` and running `conda install -file=requirements-dev.txt` would work. Since scikit-learn depends on scipy and numpy, they will be installed. This will satisfy the requirements from setup.py.

Do we need to pin the versions of tqdm and tabulate?

**Comment by ottonemo** [comment]
Can't we do the following:
```
conda create -n skorch-dev
pip install -r requirements.txt
pip install -r requirements-dev.txt
python setup.py install
conda install pytorch -c pytorch
```
I think that solves all the issues?

**Comment by ottonemo** [comment]
Sorry, you also have to include the python version of course:
```
conda create -n skorch-dev
conda install python==3.7
pip install -r requirements.txt
pip install -r requirements-dev.txt
python setup.py install
conda install pytorch -c pytorch
```

**Comment by thomasjpfan** [comment]
When using pip, we should enable the travis cache in the `.travis.ci` file:

```yaml
cache:
  pip: true
```

**Pull request merged**
